baseurl: https://x-zheng16.github.io
languageCode: en-us
theme: hugo-theme-stack
paginate: 5
title: Xiang Zheng's Blog

# Change it to your Disqus shortname before using
disqusShortname: xiangzheng

# GA Tracking ID
googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk
DefaultContentLanguage: en

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon:

    footer:
        since: 2022
        customText:

    dateFormat:
        published: Jan 02, 2006
        lastUpdated: Jan 02, 2006 15:04 MST

    sidebar:
        emoji:
        subtitle:
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: true
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: true
        provider: waline

        # Waline client configuration see: https://waline.js.org/en/reference/client.html
        waline:
            serverURL: https://blog-comment-api-nine.vercel.app
            lang: en
            visitor:
            avatar: mp
            emoji:
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/bilibili
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/qq
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/tieba
                - https://cdn.jsdelivr.net/gh/walinejs/emojis/tw-emoji
            requiredMeta:
                - nick
                - mail
            placeholder:
            visitor: true
            locale:
                nick: Nickname
                nickError: Nickname cannot be less than 3 bytes.
                mail: Email
                mailError: Please confirm your Email address.
                link: Website
                placeholder: Comment here...
                sofa: No comment yet.
                submit: Submit
                reply: Reply
                cancelReply: Cancel reply
                comment: Comments
                more: Load More...
                preview: Preview
                emoji: Emoji
                uploadImage: Upload Image
                seconds: seconds ago
                minutes: minutes ago
                hours: hours ago
                days: days ago
                now: just now
                uploading: Uploading...
                login: Login
                logout: Logout
                admin: Admin
                word: Words
                wordHint: 'Please input comments between $0 and $1 words!\n Current word number: $2'

        # twikoo:
        #     envId: https://twikoo-red-six.vercel.app
        #     region:
        #     path:
        #     lang: en

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

    opengraph:
        twitter:
            # Your Twitter username
            site:

            # Available values: summary, summary_large_image
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: true

        # Available values: auto, light, dark
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false
              icon: home

    social:
        - identifier: github
          name: GitHub
          url: https://github.com/x-zheng16
          params:
              icon: brand-github

        # - identifier: twitter
        #   name: Twitter
        #   url: https://twitter.com
        #   params:
        #       icon: brand-twitter

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    goldmark:
        renderer:
            ## Set to true if you have HTML content inside Markdown
            unsafe: false
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
